name: Run bot

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10-dev]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up configuration
      run: |
        curl https://nekobin.com/raw/foteqedafo -o amime.ini
        curl https://nekobin.com/raw/kepirenesi -o amime/config.py
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Start the bot
      run: |
        python -m amime --mode=test